apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  creationTimestamp: '2022-08-03T18:21:06Z'
  generation: 1
  name: kedatest-address
  namespace: kedatest
spec:
  addressName: keda-test
  queueName: keda-test
  routingType: anycast
