apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-kedartemis
spec:
  secretTargetRef:
    - parameter: username
      name: artemis-credentials-secret
      key: AMQ_CLUSTER_USER
    - parameter: password
      name: artemis-credentials-secret
      key: AMQ_CLUSTER_PASSWORD
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kedartemis-consumer-scaled-object
spec:
  scaleTargetRef:
    name: amqpexample-consumer
  triggers:
    - type: artemis-queue
      metadata:
        managementEndpoint: "artemis-wconsj-0-svc.kedatest.svc.cluster.local:8161"
        queueName: "keda-test"
        queueLength: "10"
        brokerName: "amq-broker"
        brokerAddress: "keda-test"
        #restApiTemplate: # Optional. Default: "http://<<managementEndpoint>>/console/jolokia/read/org.apache.activemq.artemis:broker=\"<<brokerName>>\",component=addresses,address=\"<<brokerAddress>>\",subcomponent=queues,routing-type=\"anycast\",queue=\"<<queueName>>\"/MessageCount"
      authenticationRef:
        name: trigger-auth-kedartemis